# ============================================
# THE NONCONFORMIST - GitHub Actions Workflow
# ============================================
# Place this file at: .github/workflows/build.yml
# 
# This workflow:
# 1. Runs on every push to main branch
# 2. Auto-generates images.json manifest
# 3. Deploys to Firebase Hosting

name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  FIREBASE_PROJECT_ID: 'thenonconformistdotxyz'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # ============================================
      # 1. Checkout Repository
      # ============================================
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # ============================================
      # 2. Setup Node.js
      # ============================================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      # ============================================
      # 3. Install Dependencies
      # ============================================
      - name: Install dependencies
        run: npm install
      
      # ============================================
      # 4. AUTO-GENERATE images.json manifest
      # ============================================
      - name: Generate image manifest
        run: |
          echo "🔍 Scanning for images..."
          
          # Create Node.js script inline
          cat > generate-manifest.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          const galleries = ['LoW', 'SoL', 'R', 'SA'];
          const manifest = {};
          
          galleries.forEach(dir => {
              const dirPath = path.join(process.cwd(), 'images', dir);
              
              if (!fs.existsSync(dirPath)) {
                  console.warn(`⚠️  Directory not found: ${dirPath}`);
                  manifest[dir] = [];
                  return;
              }
              
              const files = fs.readdirSync(dirPath);
              
              manifest[dir] = files
                  .filter(file => /\.(jpe?g|png|gif|webp)$/i.test(file))
                  .map(file => {
                      const match = file.match(/^(\w+)-(\d+)\.(\w+)$/i);
                      if (match) {
                          return {
                              index: parseInt(match[2]),
                              ext: match[3]
                          };
                      }
                      return null;
                  })
                  .filter(Boolean)
                  .sort((a, b) => a.index - b.index);
              
              console.log(`📸 ${dir}: Found ${manifest[dir].length} images`);
          });
          
          fs.writeFileSync('images.json', JSON.stringify(manifest, null, 2));
          console.log('\n✅ Generated images.json');
          EOF
          
          # Run the script
          node generate-manifest.js
          
          # Show the generated manifest
          echo "📄 Generated manifest:"
          cat images.json
      
      # ============================================
      # 5. Create build artifacts
      # ============================================
      - name: Create build artifacts
        run: |
          mkdir -p dist
          cp index.html dist/
          cp styles.css dist/
          cp script.js dist/
          cp images.json dist/
          cp -r images dist/ 2>/dev/null || true
          
          echo "✅ Build artifacts created"
          ls -lah dist/
      
      # ============================================
      # 6. Upload artifacts for review
      # ============================================
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
          retention-days: 30
      
      # ============================================
      # 7. Deploy to Firebase (only on main push)
      # ============================================
      - name: Deploy to Firebase Hosting
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          target: thenonconformist
          entryPoint: './dist'
      
      # ============================================
      # 8. Notify Success
      # ============================================
      - name: Post success message
        if: success()
        run: |
          echo "✅ Build and deployment successful!"
          echo "🚀 Live at: https://thenonconformist.web.app"
          echo "📸 Manifest included with $(cat images.json | grep -o '"index"' | wc -l) total images"

  # ============================================
  # VALIDATE JOB (runs in parallel)
  # ============================================
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Check for sensitive data
        run: |
          if grep -r "AIzaSy" . --include="*.html" --include="*.js" | grep -v "node_modules" | grep -v ".git"; then
            echo "⚠️ Warning: Firebase credentials found in source. Use GitHub Secrets instead."
            exit 1
          fi
      
      - name: Validate file structure
        run: |
          if [ ! -f "index.html" ]; then
            echo "❌ index.html not found"
            exit 1
          fi
          if [ ! -f "styles.css" ]; then
            echo "❌ styles.css not found"
            exit 1
          fi
          if [ ! -f "script.js" ]; then
            echo "❌ script.js not found"
            exit 1
          fi
          echo "✅ All required files present"
      
      - name: Check image directories
        run: |
          total=0
          for dir in LoW SoL R SA; do
            if [ -d "images/$dir" ]; then
              count=$(find images/$dir -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.gif" \) | wc -l)
              echo "📸 Found $count images in $dir"
              total=$((total + count))
            else
              echo "⚠️ Directory images/$dir not found"
            fi
          done
          echo "📊 Total images across all galleries: $total"

---

# ============================================
# GITHUB SECRETS REQUIRED
# ============================================
# Add these to: Settings → Secrets and variables → Actions

# FIREBASE_SERVICE_ACCOUNT:
#   (Copy JSON from Firebase Console → Project Settings → Service Accounts)

---

# ============================================
# PACKAGE.JSON (Required for npm install)
# ============================================

# {
#   "name": "thenonconformist",
#   "version": "1.0.0",
#   "description": "The Nonconformist - Photography Portfolio",
#   "scripts": {
#     "deploy": "firebase deploy",
#     "generate-manifest": "node generate-manifest.js"
#   },
#   "dependencies": {},
#   "devDependencies": {}
# }

---

# ============================================
# FIREBASE.JSON (Required for Firebase Hosting)
# ============================================

# {
#   "hosting": {
#     "public": "dist",
#     "ignore": [
#       "firebase.json",
#       "**/.*",
#       "**/node_modules/**"
#     ],
#     "rewrites": [
#       {
#         "source": "**",
#         "destination": "/index.html"
#       }
#     ],
#     "headers": [
#       {
#         "source": "images.json",
#         "headers": [
#           {
#             "key": "Cache-Control",
#             "value": "public, max-age=300"
#           }
#         ]
#       }
#     ]
#   }
# }