# ============================================
# THE NONCONFORMIST - GitHub Actions Workflow
# ============================================
# Place this file at: .github/workflows/build.yml
# 
# This workflow:
# 1. Runs on every push to main branch
# 2. Auto-generates images.json manifest (UNIVERSAL - ANY FILENAME)
# 3. Auto-generates SEO sitemaps
# 4. Deploys to Firebase Hosting

name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  FIREBASE_PROJECT_ID: 'thenonconformistdotxyz'
  SITE_URL: 'https://thenonconformist.xyz'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # ============================================
      # 1. Checkout Repository
      # ============================================
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # ============================================
      # 2. Setup Node.js
      # ============================================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      # ============================================
      # 3. Install Dependencies
      # ============================================
      - name: Install dependencies
        run: npm install
      
      # ============================================
      # 4. AUTO-GENERATE images.json manifest
      # UPDATED: Now detects ALL images regardless of filename
      # ============================================
      - name: Generate image manifest
        run: |
          echo "🔍 Scanning for images..."
          
          # Create Node.js script inline
          cat > generate-manifest.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          const galleries = ['LoW', 'SoL', 'R', 'SA'];
          const manifest = {};
          const validExtensions = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'JPG', 'JPEG', 'PNG', 'GIF', 'WEBP'];
          
          function getExtension(filename) {
              return path.extname(filename).slice(1);
          }
          
          function isValidImage(filename) {
              const ext = getExtension(filename);
              return validExtensions.includes(ext);
          }
          
          galleries.forEach(dir => {
              const dirPath = path.join(process.cwd(), 'images', dir);
              
              if (!fs.existsSync(dirPath)) {
                  console.warn(`⚠️  Directory not found: ${dirPath}`);
                  manifest[dir] = [];
                  return;
              }
              
              const files = fs.readdirSync(dirPath);
              
              // First pass: collect all valid images
              const validImages = files
                  .filter(file => isValidImage(file))
                  .map(file => ({
                      filename: file,
                      ext: getExtension(file)
                  }));
              
              // Sort alphabetically
              validImages.sort((a, b) => a.filename.localeCompare(b.filename));
              
              // Assign sequential indices
              manifest[dir] = validImages.map((img, idx) => ({
                  index: idx + 1,
                  ext: img.ext,
                  originalName: img.filename
              }));
              
              console.log(`📸 ${dir}: Found ${manifest[dir].length} images`);
          });
          
          fs.writeFileSync('images.json', JSON.stringify(manifest, null, 2));
          console.log('\n✅ Generated images.json');
          console.log('\n📊 Manifest Summary:');
          let totalImages = 0;
          Object.keys(manifest).forEach(gallery => {
              const count = manifest[gallery].length;
              totalImages += count;
              console.log(`   ${gallery}: ${count} images`);
          });
          console.log(`   Total: ${totalImages} images`);
          EOF
          
          # Run the script
          node generate-manifest.js
          
          # Show the generated manifest (first 50 lines)
          echo ""
          echo "📄 Generated manifest (preview):"
          head -n 50 images.json
      
      # ============================================
      # 5. AUTO-GENERATE SEO Sitemaps
      # ============================================
      - name: Generate SEO sitemaps
        run: |
          echo "🗺️  Generating SEO sitemaps..."
          
          cat > generate-sitemaps.js << 'EOF'
          const fs = require('fs');
          const baseUrl = '${{ env.SITE_URL }}';
          const now = new Date().toISOString().split('T')[0];
          
          // Load images manifest
          const manifest = JSON.parse(fs.readFileSync('./images.json', 'utf8'));
          
          // Gallery names
          const galleries = {
            'LoW': 'Language of Windows',
            'SoL': 'Snapshots of Life',
            'R': 'Reflections',
            'SA': 'Street Art'
          };
          
          // Generate main sitemap
          const mainSitemap = `<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>${baseUrl}/</loc>
              <lastmod>${now}</lastmod>
              <changefreq>weekly</changefreq>
              <priority>1.0</priority>
            </url>
          </urlset>`;
          
          fs.writeFileSync('./sitemap.xml', mainSitemap);
          console.log('✅ Main sitemap generated');
          
          // Generate image sitemap
          let imageEntries = '';
          let totalImages = 0;
          
          Object.keys(manifest).forEach(galleryKey => {
            const galleryName = galleries[galleryKey] || galleryKey;
            const images = manifest[galleryKey];
            
            images.forEach(img => {
              const imageUrl = `${baseUrl}/images/${galleryKey}/${encodeURIComponent(img.originalName)}`;
              const caption = `The Nonconformist - ${galleryName}`;
              const title = img.originalName.replace(/\.(jpg|jpeg|png|webp|gif)$/i, '');
              
              imageEntries += `
              <image:image>
                <image:loc>${imageUrl}</image:loc>
                <image:caption>${caption}</image:caption>
                <image:title>${title}</image:title>
              </image:image>`;
              
              totalImages++;
            });
          });
          
          const imageSitemap = `<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
                  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
            <url>
              <loc>${baseUrl}/</loc>${imageEntries}
            </url>
          </urlset>`;
          
          fs.writeFileSync('./sitemap-images.xml', imageSitemap);
          console.log(`✅ Image sitemap generated (${totalImages} images)`);
          EOF
          
          node generate-sitemaps.js
      
      # ============================================
      # 6. Create build artifacts
      # ============================================
      - name: Create build artifacts
        run: |
          mkdir -p dist
          cp index.html dist/
          cp styles.css dist/
          cp script.js dist/
          cp images.json dist/
          cp sitemap.xml dist/
          cp sitemap-images.xml dist/
          cp robots.txt dist/ 2>/dev/null || echo "User-agent: *\nAllow: /\nSitemap: ${{ env.SITE_URL }}/sitemap.xml" > dist/robots.txt
          cp humans.txt dist/ 2>/dev/null || true
          cp site.webmanifest dist/ 2>/dev/null || true
          cp favicon.ico dist/ 2>/dev/null || true
          cp -r images dist/ 2>/dev/null || true
          
          echo "✅ Build artifacts created"
          ls -lah dist/
      
      # ============================================
      # 7. Upload artifacts for review
      # ============================================
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
          retention-days: 30
      
      # ============================================
      # 8. Deploy to Firebase (only on main push)
      # ============================================
      - name: Deploy to Firebase Hosting
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          target: thenonconformist
          entryPoint: './dist'
      
      # ============================================
      # 9. Notify Success
      # ============================================
      - name: Post success message
        if: success()
        run: |
          echo "✅ Build and deployment successful!"
          echo "🚀 Live at: ${{ env.SITE_URL }}"
          echo "📸 Manifest included with $(cat images.json | grep -o '"index"' | wc -l) total images"
          echo "🗺️  Sitemaps generated and deployed"

  # ============================================
  # VALIDATE JOB (runs in parallel)
  # ============================================
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Check for sensitive data
        run: |
          if grep -r "AIzaSy" . --include="*.html" --include="*.js" | grep -v "node_modules" | grep -v ".git"; then
            echo "⚠️ Warning: Firebase credentials found in source. Use GitHub Secrets instead."
            exit 1
          fi
      
      - name: Validate file structure
        run: |
          if [ ! -f "index.html" ]; then
            echo "❌ index.html not found"
            exit 1
          fi
          if [ ! -f "styles.css" ]; then
            echo "❌ styles.css not found"
            exit 1
          fi
          if [ ! -f "script.js" ]; then
            echo "❌ script.js not found"
            exit 1
          fi
          echo "✅ All required files present"
      
      - name: Check image directories
        run: |
          total=0
          for dir in LoW SoL R SA; do
            if [ -d "images/$dir" ]; then
              count=$(find images/$dir -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.gif" \) | wc -l)
              echo "📸 Found $count images in $dir"
              total=$((total + count))
            else
              echo "⚠️ Directory images/$dir not found"
            fi
          done
          echo "📊 Total images across all galleries: $total"
      
      - name: Validate SEO files
        run: |
          echo "Checking SEO files..."
          [ -f "robots.txt" ] && echo "✅ robots.txt exists" || echo "⚠️ robots.txt missing"
          [ -f "humans.txt" ] && echo "✅ humans.txt exists" || echo "ℹ️ humans.txt optional"
          [ -f "site.webmanifest" ] && echo "✅ site.webmanifest exists" || echo "⚠️ site.webmanifest missing"